version: '3.9'

networks:
  app-network:
    driver: bridge

services:
  db:
    build: ./postgres
    container_name: postgres-db
    environment: 
      POSTGRES_USER: user123
      POSTGRES_PASSWORD: 111222
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build: .
    restart: always
    volumes:
      - ./src:/app/src
      - /app/node_modules
    container_name: node-app
    environment: 
      DB_HOST: db
      DB_USERNAME: user123
      DB_PASSWORD: 111222
      DB_NAME: appdb
      PORT: 4000
    ports:
      - "4000:4000"
    depends_on:
      - db
    networks:
      - app-network
volumes:
  pgdata: